import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React, { FC } from 'react';
import { ThemeProvider } from '@/components/theme-provider';
import { ToastProvider } from '@/components/toast-provider';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Realtime Chat Messenger',
  description: 'Generated by create next app',
};

type LayoutProps = {
  children: React.ReactNode;
}

const RootLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang='en' className='h-full'>
      <body className={cn(inter.className, 'h-full')}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <ToastProvider>
            {children}
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
